### ISSUE TITLE
fetch https pages using scrapy + crawlera

### ISSUE THREAD

**Issue by amralaaalex** [scrapy-plugins/scrapy-crawlera#56] opened 2018-09-04 09:14 UTC
in crawlera they wrote:
To fetch HTTPS pages you will need to download and install the following certificate in your HTTP client or disable SSL certificate verification:
I am getting timeout error when I try to fetch https pages, but it works fine if I disable cralwera or when I use crawlera to fetch http pages
I do not know how to disable SSL certificate verification or how to install cralwera https certificate, I have downloaded cralwera https certificate, double clicked on it, followed the wizard but nothing changed

**Comment by UnitedColorsOfNerd** [comment] 2018-09-11 06:02
I have the same issue. works fine with http pages but any https page is timing out.

**Comment by tcurvelo** [comment] 2018-10-27 19:38
Is this a problem yet? I can't reproduce the error with `scrapy-crawlera`. I've tried the spider below::

```
# -*- coding: utf-8 -*-
import json
import os
import scrapy


class HttpbinSpider(scrapy.Spider):
    name = 'httpbin'
    allowed_domains = ['httpbin.org']
    start_urls = ['https://httpbin.org/headers']
    crawlera_enabled = True
    crawlera_apikey = os.getenv('CRAWLERA_APIKEY')
    custom_settings = {
        'DOWNLOADER_MIDDLEWARES': {'scrapy_crawlera.CrawleraMiddleware': 610}
    }

    def parse(self, response):
        return json.loads(response.text)
```

**Comment by eLRuLL** [comment] 2018-12-24 23:37
@amralaaalex could you please clarify if this is still a problem for you? If not we'll be closing this issue on the following days. Kind Regards.

**Comment by hcoura** [comment] 2019-01-22 18:16
It seems this isn't a issue anymore. Closing it, feel free to reopen with problem clarification.

**Closed by hcoura** 2019-01-22 18:16 UTC
